test = {
    "You want to improve the relevance of an ad with a particular set of keywords. The goal is to increase the\u2026": "<li>Highlighting product uniqueness.</li><li>Improving the navigation of the landing page.</li><li><span style=\"text-decoration: underline;\"><strong>Adding more negative keywords.</strong></span></li><li>Focusing on connecting to a wider audience.</li>",
    "When creating an ad, how does Greg know what it will look like to his potential customers?": "<li><span style=\"text-decoration: underline;\"><strong>As he types in his URL, headline, and description, a preview of the mobile and desktop versions of his ad will appear.</strong></span></li><li>Google provides examples of desktop ads using the keywords selected in the campaign to create a generic preview.</li><li>Greg can see previews of all his ads by logging into his Google My Business account and choosing the Preview tab.</li><li>Greg must type in the specific keywords he\u2019s targeting once his ad has been approved, then view it in a browser.</li>",
    "Asam is learning about Google Ads Search. He wants to know why a marketer might use callout extensions. For which activity are callout extensions beneficial?": "<li><span style=\"text-decoration: underline;\"><strong>Highlight key information and unique selling points of a business</strong></span></li><li>Provide potential customers with the ability to call a business directly from an ad</li><li>Allow users to navigate to specific pages directly from an ad</li><li>Give potential customers the ability to contact a business via a text message</li>",
    "Google Ads was designed to help businesses achieve online success. To accomplish this, Google Ads was built\u2026": "<li>Sales, consideration, and integrity</li><li>Growth, reach, and traffic</li><li><span style=\"text-decoration: underline;\"><strong>Relevance, control, and results</strong></span></li><li>Influence, awareness, and promotion</li>",
    "Your client, Vince\u2019s Veggies, wants to increase downloads of their popular recipe printouts. You suggest they create ad groups based on the cooking categories that appear on their website. What will they need to create in their first Google Search Ad group? (Choose two.)": "<li>Device types</li><li><span style=\"text-decoration: underline;\"><strong>Keyword list</strong></span></li><li><span style=\"text-decoration: underline;\"><strong>Default bid amount</strong></span></li><li>Delivery times</li><li>Country targets</li>",
    "What\u2019s the maximum number of ad extensions that can show for a particular query or device at any given time?": "<li>3</li><li>1</li><li>2</li><li><strong><span style=\"text-decoration: underline;\">4</span></strong></li>",
    "What is a main benefit of using Search Audience solutions?": "<li>They get detailed analytical insights about search network performance.</li><li>They identify ad extension opportunities to improve average click-through rates.</li><li>They automatically generate new keyword and ad content suggestions.</li><li><strong><span style=\"text-decoration: underline;\">They can help send the right message to the right customer with the right bid.</span></strong></li>",
    "A water-sports company specializes in custom-made watercrafts and accessories. Their marketing manager\u2026": "<li>Rowboat paddling</li><li>Boats and ships</li><li><span style=\"text-decoration: underline;\"><strong>A green boat paddle</strong></span></li><li><span style=\"text-decoration: underline;\"><strong>Travel on a paddle ship</strong></span></li><li>Boat adventure</li>",
    "What does Performance Planner automatically do?": "<li>Sets your ad budget for maximum growth</li><li><span style=\"text-decoration: underline;\"><strong>Forecasts how your current campaigns will perform in the future</strong></span></li><li>Recommends the perfect ad structure for your budget</li><li>Uses machine learning to target new demographics</li>",
    "Clara is an advertising director who has been tasked with optimizing her company\u2019s Google Search campaign\u2026": "<li>To compare the efficacy of her ad text creative with that of other ads</li><li>To judge the popularity of her website compared to others</li><li>To understand the network performance of her website</li><li><strong><span style=\"text-decoration: underline;\">To find how close her campaign is from potential ideal results</span></strong></li>",
    "Siona needs to make sure her ads are getting a minimum number of impressions on the top of the page\u2026": "<li>Maximize clicks</li><li>Target return on ad spend (Target ROAS)</li><li><span style=\"text-decoration: underline;\"><strong>Target impression share</strong></span></li><li>Target cost-per-acquisition (tCPA)</li>",
    "Which statement is true about serving relevant ad extensions?": "<li>They provide advertisers with additional insights within the search term report.</li><li><span style=\"text-decoration: underline;\"><strong>They encourage users to make more informed decisions and take action.</strong></span></li><li>They generate new creative suggestions for both keywords and ads.</li><li>They prevent all irrelevant traffic from clicking on your ads.</li>",
    "Jimmy sells televisions on his website. He notices he\u2019s getting traffic from searches for a brand he\u2026": "<li>Common misspellings and synonyms of his keywords will still allow his ads to be shown.</li><li><span style=\"text-decoration: underline;\"><strong>His ads won\u2019t be shown to users searching for the uncarried brand.</strong></span></li><li>Jimmy\u2019s ads will appear at a lower rate when users search for the television brand.</li><li>Ads for Jimmy\u2019s business will be shown to the widest possible audience.</li>",
    "What is the minimum number of users a remarketing list must have before being used with a Remarketing\u2026": "<li><span style=\"text-decoration: underline;\"><strong>1,000 users</strong></span></li><li>100 users</li><li>10,000 users</li><li>500 users</li>",
    "You\u2019re working on a Google Search Ad that\u2019s not performing as expected. You specifically want more users to\u2026": "<li>Increasing the trustworthiness of the website.</li><li><span style=\"text-decoration: underline;\"><strong>Changing the call-to-action message of the ad.</strong></span></li><li>Reducing the bid rate on the ad.</li><li>Modifying the ad\u2019s landing page to load faster.</li>",
    "Match these Search Audience solutions with the benefits they can bring to": "<li><strong>Remarketing Lists for Search Ads </strong>\u2014 To help reach people who have engaged with your website or YouTube channel in the past</li><li><strong>Detailed Demographics</strong> \u2014 To reach people based on the likelihood of their marital status, education, parenting stage, and home ownership</li><li><strong>In-Market Audiences </strong>\u2014 To drive consideration among people who are actively researching the products or services you offer</li><li><strong>Customer Match</strong> \u2014 To upload your own data into Google Ads and reach custom segments across devices </li>",
    "Your Google Search text ad has three main components. The first is a headline, and the second is a description": "<li><span style=\"text-decoration: underline;\"><strong>The URL displaying your website address.</strong></span></li><li>The promotion behind your advertisement.</li><li>The phone number of your business.</li><li>The location of your business.</li>",
    "Reggie manages the online marketing campaigns for a vitamin and supplement store. He launched a\u2026": "<li>More followers on the store\u2019s social media presence.</li><li><span style=\"text-decoration: underline;\"><strong>Getting more customers to learn about his products.</strong></span></li><li>More online sales through Reggie\u2019s online store.</li><li>E-mail sign-ups from people interested in a healthy lifestyle.</li>",
    "You\u2019d like to improve an ad\u2019s perceived quality during an ad auction. What aspect of the ad will be most\u2026": "<li>Removing an extension from the ad.</li><li><strong><span style=\"text-decoration: underline;\">Improving the navigability of the landing page.</span></strong></li><li>Increasing the bid amount of the ad.</li><li>Determining the location of users.</li>",
    "Brian manages his company\u2019s Google Search Ads campaign. He regularly reviews the optimization score to make\u2026": "<li>Testing and reporting on the speed of Brian\u2019s websites</li><li><span style=\"text-decoration: underline;\"><strong>Key aspects of his accounts, including statistics, settings, and industry trends</strong></span></li><li>Judging ad popularity on social media</li><li>Comparing Brian\u2019s sales with ad serving data</li>",
    "Silly Sayings is seeing a lot of website traffic, but the company wants to generate more qualified leads\u2026": "<li>By presenting users with catalog options for a product.</li><li>By dynamically using negative keywords, based on a user\u2019s website content.</li><li>By attracting users with creative assets.</li><li><strong><span style=\"text-decoration: underline;\">By providing users with relevant information up-front.</span></strong></li>",
    "What Search Network text ad component provides up to three fields of 30 characters each?": "<li><span style=\"text-decoration: underline;\"><strong>The headline component</strong></span></li><li>The website URL component</li><li>The conversion component</li><li>The description component</li>",
    "Rashid wants to raise awareness of his brand and build campaigns focused on branded terms. He doesn\u2019t have\u2026": "<li>Maximize conversions</li><li>Target return on ad spend (Target ROAS)</li><li>Enhanced cost-per-click (eCPC)</li><li><strong><span style=\"text-decoration: underline;\">Target impression share</span></strong></li>",
    "Carrie owns a gardening store and uses a website to promote all the products she sells. A user saw a Google\u2026": "<li>Watching a YouTube video on rose cultivation.</li><li><span style=\"text-decoration: underline;\"><strong>Searching for related gardening information.</strong></span></li><li>Browsing Carrie\u2019s store website.</li><li>Reading an e-mail from Carrie\u2019s business.</li>",
    "John\u2019s company makes a great product and customers are happy with their purchases. Unfortunately, few\u2026": "<li><span style=\"text-decoration: underline;\"><strong></strong><strong>With multiple headline and description options, responsive ads can compete in more auctions for a wider range of search terms.</strong></span></li><li>With higher per-sale transaction returns, responsive ads increase the working budget for an advertiser\u2019s active campaigns.</li><li><span style=\"text-decoration: underline;\"><strong>With lower costs-per-click, advertisers using responsive ads can afford to be in more daily auctions.</strong></span></li><li>With machine learning making the decisions, responsive ads are given preferential treatment by the system in every auction.</li>",
    "You\u2019ve been tasked with marketing a new line of plumbing services, but you have a set budget you can\u2019t exceed.": "<li>Google Ads guarantees phone calls to your business.</li><li><span style=\"text-decoration: underline;\"><strong>Google Ads gives you control over your budget.</strong></span></li><li>Google Ads allows you to cap the number of ads you pay for, based on your business.</li><li>Google Ads offers separate auctions for low budgets.</li>",
    "Karen has evaluated her Google Search Ads campaign\u2019s optimization score after noticing that the campaign\u2019s\u2026": "<li>It will gradually improve by the end of the week.</li><li>It will improve the end of the day.</li><li><span style=\"text-decoration: underline;\"><strong>It will improve upon acceptance.</strong></span></li><li>It will improve by the end of the month.</li>",
    "Swee Yin\u2019s fashion-apparel department store runs a popular biannual sale on men\u2019s hats, with large discounts and surprise bonus items. She wants to tailor her Google Search campaign to highlight this sale. How can Google Search campaigns be tailored to promote her company\u2019s sales event?": "<li>By choosing \u201cleads\u201d as the campaign goal.</li><li><strong>By creating a new ad group for the sale.</strong></li><li><strong>By setting campaign start/end dates.</strong></li><li>By adding coupon alerts to people nearby the store.</li><li>By targeting specific device operating systems.</li>",
    "A golf enthusiast regularly watches instructional videos about golf, has recently searched for the best golf\u2026": "<li><span style=\"text-decoration: underline;\"><strong>Affinity Audience</strong></span></li><li>In-Market Audience</li><li>Detailed Demographics</li><li>Similar Audiences for Search</li>",
    "Samira recently opened an online potted plant store and needs to promote it. She chose Google Ads because\u2026": "<li>TV campaigns, which promote her products directly to consumers while they\u2019re watching their favorite network and cable TV programs.</li><li><span style=\"text-decoration: underline;\"><strong>Shopping campaigns, which promote her products by giving consumers detailed informationabout what she\u2019s selling before they click her ad.</strong></span></li><li>Social media campaigns, which showcase her products to users while they browse their favorite social-media platforms.</li><li>App campaigns, which can increase engagement, app installs, and even in-app actions, such as ordering her products.</li>",
    "When visibility is the campaign goal, which bidding strategy should an advertiser choose?": "<li>Maximize Conversions</li><li>Maximize clicks</li><li><span style=\"text-decoration: underline;\"><strong>Target impression share</strong></span></li><li>Enhanced cost-per-click (eCPC)</li>",
    "Yan wants to attract customers specifically searching on Google for Time-B-Gone, his company\u2019s unique office\u2026": "<li><span style=\"text-decoration: underline;\"><strong>Landing pages from standard ad groups</strong></span></li><li>Page feeds</li><li>URL filtering</li><li>Categories from dynamic search engines</li>",
    "You are working to improve the quality score of a Google Search ad by increasing your eCTR. Your goal is to\u2026": "<li><span style=\"text-decoration: underline;\"><strong>Adding more specifics to the ad.</strong></span></li><li>Tweaking the speed of your website.</li><li>Decreasing the bid for the ad.</li><li>Cloning the ad multiple times.</li>",
    "Helen\u2019s Heating and Air (HHA) wants to encourage interest in their new smart refrigerators. They know that\u2026": "<li>WidgetCo customer support</li><li>Refrigerator reviews WidgetCo</li><li><span style=\"text-decoration: underline;\"><strong>Smart refrigerator reviews</strong></span></li><li><span style=\"text-decoration: underline;\"><strong>Energy-efficient fridge</strong></span></li><li>WidgetCo refrigerator installation</li>",
    "John\u2019s Plumbing prides itself on excellent customer service, especially during after-hours service calls\u2026": "<li>Networks</li><li>Devices</li><li>Ad extensions</li><li><strong><span style=\"text-decoration: underline;\">Ad scheduling</span></strong></li>",
    "Francis wants to increase his Google Ads skills and optimize results for his clients. What two best practices\u2026": "<li><span style=\"text-decoration: underline;\"><strong>Include three to five ads, and at least three extensions in each ad group.</strong></span></li><li>Set a keyword bid of at least $10 for each active ad group.</li><li>Implement one ad per ad group keyword, to a maximum of 100 ads.</li><li>Choose a minimum 100 keywords of all match types to capture traffic.</li><li><strong><span style=\"text-decoration: underline;\">Optimize the campaign\u2019s ad rotation for clicks or conversion actions.</span></strong></li>",
    "Maria has been told that she should use the Performance Planner on a monthly basis. Why should she do so?": "<li>To analyze demographic performance</li><li><span style=\"text-decoration: underline;\"><strong>To react to ever-changing external factors</strong></span></li><li>To review new keyword opportunities</li><li>To check for status issues</li>",
    "What are two ways that Performance Planner can help reveal the possibilities across all your Google Ads\u2026": "<li>Distribution</li><li><span style=\"text-decoration: underline;\"><strong>Validation</strong></span></li><li><span style=\"text-decoration: underline;\"><strong>Simulation</strong></span></li><li>Instrumentation</li><li>Differentiation</li>",
    "Match each ad extension with the benefit it brings to a user\u2019s ad experience.": "fuck you",
    "It is 10 a.m. and you are sitting in a train station in London, looking through your calendar on your tablet.": "<li><strong>Time</strong> \u2014 It is 10 a.m.</li><li><strong>Interest</strong> \u2014 I love historical sites and San Francisco.</li><li><strong>Intent</strong> \u2014 I need to book a boat ride.</li><li><strong>Device</strong> \u2014 I am using my tablet.</li><li><strong>Location</strong> \u2014 I am sitting in a train station in London.  </li>",
    "Priya only has $500 a month to spend on her campaign, but she needs to drive as many potential customers as\u2026": "<li>Target impression share</li><li>Enhanced cost-per-click (eCPC)</li><li><span style=\"text-decoration: underline;\"><strong>Maximize clicks</strong></span></li><li>Target return on ad spend (tROAS)</li>",
    "Your company provides home-maintenance services, and you want to reach more potential customers\u2026": "<li>Your ads will be placed on all search engines.</li><li>With Google Ads, you always pay using cost-per-reach, predetermined by your budget.</li><li><span style=\"text-decoration: underline;\"><strong>You can set your own budget and can change it at any time.</strong></span></li><li>Machine models automatically determine your advertising budget.</li>",
    "Carlton runs an adventure excursion company in South America. He\u2019d like to increase the number of people\u2026": "<li>Watching an online video about South America.</li><li><span style=\"text-decoration: underline;\"><strong>Researching South American holiday destinations online.</strong></span></li><li>Looking up passport rules for South America.</li><li>Browsing an adventure activities website.</li>",
    "Google Ads was constructed around three core principles, focused on helping businesses reach their online\u2026": "<li><span style=\"text-decoration: underline;\"><strong>Control and results</strong></span></li><li>Credits and context</li><li>Options and tracking</li><li>Profit and privacy</li>",
    "You\u2019ve seen great results from your Google Search campaigns when using Remarketing Lists for Search Ads\u2026": "<li>Removing Similar Audiences from Remarketing campaigns</li><li>Use Similar Audiences to re-connect with past visitors to your site</li><li>Increase the size of your remarketing lists by decreasing the size of your Similar Audiences lists</li><li><strong><span style=\"text-decoration: underline;\">Use Similar Audiences to find new visitors for your site</span></strong></li>",
    "Bernadette\u2019s in charge of marketing a new product in a highly competitive segment. She\u2019s planning to launch\u2026": "<li>It will bring Bernadette\u2019s website better page rank.</li><li>Ads from Bernadette\u2019s campaign will appear in traditional media with related content.</li><li><strong>Her business will have a competitive presence with similar businesses during searches.</strong></li><li>Users will receive ads when physically near any of Bernadette\u2019s storefronts.</li>",
    "Mario is working on a text ad that will run on the Google Search Network. He filled in each component with\u2026": "<li>The headline component</li><li>The URL component</li><li>The banner component</li><li><strong><span style=\"text-decoration: underline;\">The description component</span></strong></li>",
    "Rebecca is a marketing executive at an airline company. She has been asked to plan her company\u2019s online\u2026": "<li>Performance Planner is free to use with any merchant-hosted storefront.</li><li><span style=\"text-decoration: underline;\"><strong>Performance Planner forecasting is powered by billions of Google searches conducted eachweek.</strong></span></li><li><span style=\"text-decoration: underline;\"><strong>Performance Planner leverages machine learning for forecasting.</strong></span></li><li>Performance Planner will help her identify funds from other operational budgets to allocate to marketing.</li><li>Performance Planner integrates with other budgeting software, such as QuickBooks.</li>",
    "What two ad extension types can also be served as automated ad extensions? (Choose two.)": "<li>Location extension</li><li>Promotion extension</li><li>Call extension</li><li><span style=\"text-decoration: underline;\"><strong>Sitelink extension</strong></span></li><li><span style=\"text-decoration: underline;\"><strong>Callout extension</strong></span></li>",
    "An advertising executive takes over a Google Search ads campaign. On his Google Ads Recommendations page he\u2026": "<li><span style=\"text-decoration: underline;\"><a><strong>The campaign could be improved by 60% if the listed recommendations are followed</strong></a><strong>.</strong></span></li><li>The campaign is 60% less optimal than other company campaigns.</li><li>The campaign is running 40% over budget.</li><li>The campaign is 40% optimized for the given keywords chosen by the previous campaign manager.</li>",
    "What\u2019s the primary benefit of using structured snippet extensions in your ads?": "<li>Lets you show your business address, phone number, and a map marker alongside your ad text.</li><li>Allows potential customers to navigate to specific pages of your website directly from the ad.</li><li><strong><span style=\"text-decoration: underline;\">Gives users specific information about what you\u2019re offering, before they visit your website.</span></strong></li><li>Lets you quickly display information about your promotions without having to update every ad.</li>",
    "Automated bidding does the heavy lifting for advertisers on Google Ads. What does automated bidding use to\u2026": "<li>Ad extensions</li><li>Manual control </li><li>Seller ratings</li><li><strong><span style=\"text-decoration: underline;\">Machine learning</span></strong></li>",
    "Trevor owns a manufacturing business that makes specialized hiking and rock-climbing gear. He\u2019s a small\u2026": "<li>Video</li><li>Search</li><li>Shopping</li><li><strong><span style=\"text-decoration: underline;\">Display</span></strong></li>",
    "Bob\u2019s electronics company is launching a new television called UltraView1000. Bob decides to use broad\u2026": "<li>Bob\u2019s ad will appear if the search terms only contain his brand of television, UtraView1000.</li><li><span style=\"text-decoration: underline;\"><strong>Bob\u2019s ad will appear if search terms contain some variation of his keyword, such as \u201cTV.\u201d</strong></span></li><li>Bob\u2019s ad will only appear if the search terms contain the exact keyword, \u201ctelevision.\u201d</li><li>Bob\u2019s ad will only appear if the search term is exactly \u201ctelevision\u201d with additional words before and after.</li>",
    "Yan is working on a Remarketing List for Search Ads campaign. Which user could be added to a valid Remarket\u2026": "<li>Someone who has heard of his company\u2019s business but never visited the company\u2019s website</li><li><span style=\"text-decoration: underline;\"><strong>Someone who has added items to a shopping basket on his company\u2019s website but thenabandoned it</strong></span></li><li>Someone who has seen his company\u2019s ads but never clicked on them</li><li>Someone who has visited numerous similar websites</li>",
    "As an advertiser, creating your first text ad in Google Ads is a simple five\u2026": "<li><strong><span style=\"text-decoration: underline;\">First step:</span></strong> Sign in to the Google Ads account where you wish to make the text ad.</li><li><strong><span style=\"text-decoration: underline;\">Second Step:</span></strong> In the page menu on the left of the screen, select Ads &amp; Extensions.</li><li><strong><span style=\"text-decoration: underline;\">Third Step:</span></strong> Choose the + button, and then select Text Ad from the available options.</li><li><strong><span style=\"text-decoration: underline;\">Fourth Step:</span></strong> Enter the headlines, URL, and description lines you wish to use.</li><li><strong><span style=\"text-decoration: underline;\">Fifth Step: </span></strong>Ensure the ad meets Google\u2019s editorial guidelines, and press Save Ad.</li>",
    "What\u2019s a key objective in delivering ad extensions?": "<li><span style=\"text-decoration: underline;\"><strong>Providing the right users with the right information at the right moment.</strong></span></li><li>Opening up additional ad space to extend character limits.</li><li>Making ads more appealing with the use of image and video assets.</li><li>Giving users control over the types of ads that they see.</li>",
    "Ad extensions assist in providing users with which two things they want from their search experience?": "<li>Attractive imagery</li><li><span style=\"text-decoration: underline;\"><strong>Relevant information</strong></span></li><li><span style=\"text-decoration: underline;\"><strong>Information based on their moment</strong></span></li><li>Product and service comparisons</li><li>News items related to their search</li>",
    "Ginger\u2019s working on creating her first Google Search Ad. She wants to create an inviting and relevant ad,\u2026": "<li>has a larger font size</li><li>is listed after search results</li><li>includes at least two different colors</li><li><span style=\"text-decoration: underline;\"><strong>has a relevant headline</strong></span></li><li><span style=\"text-decoration: underline;\"><strong>includes a current promotion</strong></span></li>",
    "Lisa sells kitchen furniture through her website. While her sales are stable, she\u2019s concerned that they\u2019re\u2026": "<li><span style=\"text-decoration: underline;\"><strong>Her business will have a competitive presence with similar businesses during searches.</strong></span></li><li>Her business will have a higher ranking in organic search results.</li><li>Ads for her business will appear across a variety of digital and traditional media.</li><li>Potential customers will be automatically directed to her business website.</li>",
    "Jerry\u2019s managing a Google Search campaign and would like to improve the position in which his ads appear\u2026": "<li>Remove ad extensions.</li><li><span style=\"text-decoration: underline;\"><strong>Create a helpful, relevant landing page for the ad.</strong></span></li><li>Reduce the number of words in the ad.</li><li>Control user signals and attributes.</li>",
    "What are two main benefits of using Search Audience solutions? (Choose two.)": "<li><span style=\"text-decoration: underline;\"><strong>Making the right bids when certain groups of people are searching for your product or services</strong></span></li><li>Identifying the most effective ad schedules to get the best results from your budget</li><li><span style=\"text-decoration: underline;\"><strong>Reaching different audience segments with unique messaging that is highly relevant to them</strong></span></li><li>Reviewing missed opportunities with regards to ad extensions and ad variations</li><li>Getting detailed insights into which bid strategies can work best for your search network campaigns</li>",
    "How is using non-last-click attribution conversions useful for Performance Planner forecasts?": "<li>To find growth opportunities regarding device targeting</li><li><span style=\"text-decoration: underline;\"><strong>To allocate budgets that drive incremental conversions</strong></span></li><li>To take advantage of seasonal trends throughout the year</li><li>To identify the most profitable location targeting</li>",
    "What can the Performance Planner assist you with?": "<li>To create an optimized copy of your existing campaign, so that it can be tested with the drafts and experiments tool</li><li>To determine which Google Ads features should be enabled to get the best performance from your campaigns</li><li>To analyze the search term report and add both keywords and negative keywords, depending on historical performance</li><li><strong><span style=\"text-decoration: underline;\">To improve return on investment so you can drive more conversions within your target CPA(cost-per-acquisition)</span></strong></li>",
    "What does layering an Affinity audience with a broad keyword targeting campaign help you do?": "<li>Reach people who have been identified as being in the mindset to buy</li><li>Reach people based on specific demographics such as marital and education status</li><li>Find new customers that share the behaviors and characteristics of your marketing audience segments</li><li><strong><span style=\"text-decoration: underline;\">Ensure your ads are only seen by people who have demonstrated a qualified interestin your service and/or product(s)</span></strong></li>",
    "What is one way that Performance Planner helps businesses increase sales?": "<li>By choosing ad types that your target demographic finds most appealing</li><li>By relying on customer feedback for optimal ad placement</li><li><span style=\"text-decoration: underline;\"><strong>By maximizing the number of conversions for a spend scenario</strong></span></li><li>By providing a discount on all ads after purchasing a license</li>",
    "Steven is an advertising executive at a large auto parts company. He uses his Google Ads Recommendations\u2026": "<li>Receive information on general trends</li><li>Stay focused on certain keywords</li><li><span style=\"text-decoration: underline;\"><strong>Apply recommendations across multiple layers of his advertising strategy</strong></span></li><li>Make use of the expanded daily update frequency</li>",
    "Singh\u2019s marketing company has created an enticing ad that receives many clicks. What effect will the ad\u2026": "<li><span style=\"text-decoration: underline;\"><strong>The higher expected click-through rate will lead to a higher Ad Rank.</strong></span></li><li>The advertiser will receive more bids in the auction.</li><li>The ad will lead to a higher cost-per-click for the advertiser.</li><li>The quality of the ad will ensure the ad\u2019s cost-per-click will be reduced by at least 40%.</li>",
    "Mary wants to run a text ad on the Google Search Network. She\u2019s new to text ads and needs to start with the\u2026": "<li><span style=\"text-decoration: underline;\"><strong>Headline, URL, Description</strong></span></li><li>Beacon, Tag, Conversion</li><li>Headline, Descriptor, Image</li><li>Tagline, AMP, Characters</li>",
    "How can Performance Planner serve your business?": "<li>By finding areas of your total budget that could contribute to marketing</li><li>By determining which of Google\u2019s ads are most appropriate for your brand</li><li>By teaching your employees the fundamentals of personal budgeting</li><li><strong><span style=\"text-decoration: underline;\">By optimizing your ad budget for maximum growth</span></strong></li>",
    "Wendy is setting up a Customer Match strategy to reach a list of prospective customers. What must she provide?": "<li>A Google remarketing tag</li><li>A linked Google Analytics account</li><li><span style=\"text-decoration: underline;\"><strong>Customer relationship management data</strong></span></li><li>Conversion tracking</li>",
    "Jim has created a Google Search ad with a bid of $5. Two other advertisers in an auction have bids of $2.50\u2026": "<li>$5</li><li><span style=\"text-decoration: underline;\"><strong>$2.51</strong></span></li><li>$4.50</li><li>$2.50</li>",
    "Trina is using automated bidding as part of her Google Ads Search bidding strategy. Why might she prefer\u2026": "<li>Location targeting is not decided by machine learning.</li><li>Machine learning will choose an ad schedule for campaigns without her input.</li><li>Machine learning will choose the keywords used to serve her ads to users.</li><li><strong><span style=\"text-decoration: underline;\">Machine learning helps her set the appropriate bid for each and every auction.</span></strong></li>",
    "Why is using the performance targets feature after utilizing the Performance Planner recommended?": "<li><span style=\"text-decoration: underline;\"><strong>This practice allows you to monitor targets set in the Performance Planner and to receive alerts and recommendations when a campaign is not on track.</strong></span></li><li>This practice allows you to ensure seasonality and budget reallocation are accounted for future periods so you can prevent your campaigns from becoming \u201cLimited by Budget\u201d.</li><li>This practice allows you to receive detailed insights from Google Analytics with regards to how website behavior is impacted after applying Performance planner recommendations.</li><li>This practice allows you to fully automate all aspects of account management to improve the likelihood of meeting performance targets.</li>",
    "What are two ways Dynamic Search Ads brings value to an advertising campaign?": "<li>It promotes advertising on social media platforms.</li><li>It allows for greater control over keywords.</li><li>It reduces the needed advertising budget.</li><li><span style=\"text-decoration: underline;\"><strong>It creates new ads automatically.</strong></span></li><li><span style=\"text-decoration: underline;\"><strong>It finds traffic an advertiser might miss.</strong></span></li>",
    "Your Google Search Ads optimization score is calculated by an algorithm that looks across key aspects of\u2026": "<li>Company sales figures</li><li>Account executives</li><li>User generated scenarios</li><li><strong>Industry data</strong></li><li><strong>Account settings</strong></li>",
    "Google Ads reviews saved text ads to ensure they meet advertising policies before being shown to users\u2026": "<li>Goals and analytics.</li><li>Length and extensions.</li><li><span style=\"text-decoration: underline;\"><strong>Content and formatting.</strong></span></li><li>Loading and site speed.</li>",
    "What\u2019s an example of an effective callout extension?": "<li>Send us a text for more information</li><li>Learn more about us</li><li>Contact our team</li><li><strong><span style=\"text-decoration: underline;\">Free returns</span></strong></li>",
    "While managing a successful Google Ads campaign, why would you choose automated bidding instead of manual\u2026": "<li>Because users intent and their likelihood to complete valuable actions for your business hardly vary based on location, time, or device</li><li>Because cross-referencing data with context to establish intent and set the appropriate bid is a more simple, direct task</li><li>Because bid automation is a standard capability in the market that allows a lesser degree of precision, based on the conversion opportunity of each auction</li><li><strong><span style=\"text-decoration: underline;\">Because given the dynamic nature of Google\u2019s auctions, the appropriate bid can often be a moving target that is challenging to reach at scale when using manual bidding</span></strong></li>",
    "What does adding callout extensions to your Google Search ads enable you to do?": "<li><span style=\"text-decoration: underline;\"><strong>Highlight information about value-adding attributes of your business, products, orservices.</strong></span></li><li>Direct users to specific pages of your website.</li><li>Extend ads with a phone number, allowing mobile users to directly call your business.</li><li>Gives you the option of driving traffic to your website or to the app store from a single text ad.</li>",
    "Bob\u2019s electronics company has quite a buzz around a new television they\u2019re launching, called UltraView1000\u2026": "<li>Bob\u2019s ad will appear if search terms contain at least one of the keywords or variations of those terms.</li><li>Bob\u2019s ad will appear if search terms contain at least one of the keywords and words right before or after them.</li><li><span style=\"text-decoration: underline;\"><strong>Bob\u2019s ad will appear if search terms contain at least all three of the keywords orvariations of those terms.</strong></span></li><li>Bob\u2019s ad will appear if the search terms contain all three of the exact keywords.</li>",
    "You want to increase the relevance of a Google Search Ad so it\u2019s more meaningful to potential customers\u2026": "<li><span style=\"text-decoration: underline;\"><strong>Selecting distinct geographic areas.</strong></span></li><li><span style=\"text-decoration: underline;\"><strong>Selecting only relevant languages in campaign setup.</strong></span></li><li>Changing the ad\u2019s call-to-action statement.</li><li>Rewriting the landing page for clarity.</li><li>Posting transparency statements on the website.</li>",
    "What content could be used for a structured snippet extension?": "<li><span style=\"text-decoration: underline;\"><strong>Berlin, London, Paris, Singapore</strong></span></li><li>Free shipping</li><li>Text an expert now</li><li>Contact our team</li>",
    "Hank wants to use a \u201cMaximize Conversions\u201d campaign with the Performance Planner. Which recommendation\u2026": "<li>Recommended campaign bid scaling</li><li>A recommended Campaign-level Target ROAS (return-on-ad-spend)</li><li>A recommended Campaign-level Target CPA (cost-per-acquisition)</li><li><strong><span style=\"text-decoration: underline;\">A recommended average daily budget</span></strong></li>",
    "Which is required for an ad to be served to a user?": "<li><span style=\"text-decoration: underline;\"><strong>The keywords must be relevant to the search term.</strong></span></li><li>The keywords must be unique to only one campaign.</li><li>The keywords must be listed in all ad groups for a company.</li><li>The search terms must be unique to a company.</li>",
    "Samira has been tasked with increasing the relevance of her company\u2019s ads. She has been told that she can\u2026": "<li>Up to 50 headlines</li><li>Up to 5 headlines</li><li><span style=\"text-decoration: underline;\"><strong>Up to 15 headlines</strong></span></li><li>Up to 25 headlines</li>",
    "Using the Performance Planner on a monthly basis allows you to optimize which two aspects of an account?": "<li>Keywords</li><li><span style=\"text-decoration: underline;\"><strong>Bids</strong></span></li><li><span style=\"text-decoration: underline;\"><strong>Budgets</strong></span></li><li>Ad extensions</li><li>Ads</li>",
    "Alex has started a Google Search campaign designed to promote his online motorcycle accessories store\u2026": "<li>By including his ad on similar motorcycle accessory store websites.</li><li>By linking to Alex\u2019s ad from related social-media groups.</li><li>By displaying Alex\u2019s ad on a website that reviews motorcycle helmets.</li><li><strong><span style=\"text-decoration: underline;\">By showing his ad to people searching for related information about helmets.</span></strong></li>",
    "What can the Performance Planner recommend?": "<li><span style=\"text-decoration: underline;\"><strong>Campaign-level Target CPA (cost-per-acquisition)</strong></span></li><li>Applying bid adjustments to specific locations</li><li>Including or excluding \u201cGoogle search partners\u201d</li><li>Using \u201cTarget impression share\u201d as an automated bid strategy</li>",
    "What\u2019s an accurate description of callout extensions?": "<li><span style=\"text-decoration: underline;\"><strong>Short, specific snippets of text that highlight value-adding attributes.</strong></span></li><li>Additional links that direct users to specific pages of a website.</li><li>A mobile-only format that enables users to contact a business via text messages.</li><li>Extends ads with a phone number, allowing mobile users to directly call a business.</li>",
    "Trina sells dolls and accessories, and doesn\u2019t have much time to update her Search campaigns with her ever\u2026": "<li>The inventory update dates can be manually set.</li><li>Lower bid rates can be utilized, based on inventory levels.</li><li><span style=\"text-decoration: underline;\"><strong>Keyword lists can be automatically created based on website offerings.</strong></span></li><li>Additional web crawlers can be employed to review her inventory.</li>",
    "Sarah\u2019s Autos sells multiple automobile brands, showcasing used, pre-owned, and new vehicles. The company\u2019s\u2026": "<li>Road</li><li>Bicycle</li><li><span style=\"text-decoration: underline;\"><strong>Car</strong></span></li><li><span style=\"text-decoration: underline;\"><strong>Automobile</strong></span></li><li>Travel</li>",
    "Which Dynamic Search Ads option allows an advertiser to group web pages under custom labels?": "<li>URL filtering</li><li>Categories</li><li>Landing pages</li><li><strong><span style=\"text-decoration: underline;\">Page feeds</span></strong></li>",
    "Francine is advertising her company\u2019s newest video-editing software and related products. She knows that\u2026": "<li>More ads in an ad group increases the chances of showing more than one ad per auction.</li><li><span style=\"text-decoration: underline;\"><strong>More ads in an ad group means more options for success in an auction.</strong></span></li><li>More ads in an ad group means they receive a higher-quality score.</li><li>More ads in an ad group means lower bounce rates for landing pages.</li>",
    "In-Market audiences would be suited to reach which user?": "<li><span style=\"text-decoration: underline;\"><strong>Someone looking to purchase a new car</strong></span></li><li>Someone researching the safety features of baby prams</li><li>Someone with a qualified interest in mountaineering</li><li>Someone excited about a new movie release</li>",
    "What ad extension is only available as a full automated ad extension?": "<li>App extension</li><li><span style=\"text-decoration: underline;\"><strong>Seller ratings extension</strong></span></li><li>Message extension</li><li>Price extension</li>",
    "How does automating your bid contribute to a successful Google Ads campaign?": "<li>Automated bidding\u2019s algorithms integrate a minimum number of signals to evaluate user intent.</li><li><span style=\"text-decoration: underline;\"><strong>Automated bidding uses machine learning to algorithmically help you set the appropriatebid for each and every auction.</strong></span></li><li>Cross-referencing data with context to establish intent and set the appropriate bid is a simple and direct task.</li><li>The customer journey has become more direct, so setting bids should be based on general user behavior.</li>",
    "Google Ads was designed to deliver three things to every advertiser: relevance, control, and results\u2026": "<li>By giving advertisers control over the number of specific actions their spend will return</li><li>By giving advertisers control over which competitors they place ads in auctions against </li><li>By giving advertisers control over the next highest bid allowed in auctions they enter</li><li><strong><span style=\"text-decoration: underline;\">By giving advertisers control over the maximum they spend per month.</span></strong></li>",
    "After running a Google Search Ads campaign for several months, Meredith notices sales of her advertised\u2026": "<li>The campaign\u2019s budget needs to be raised by 22% to be fully optimized.</li><li><span style=\"text-decoration: underline;\"><strong>The campaign could be improved by 78% if the listed recommendations are followed.</strong></span></li><li>Her campaign is being outperformed by 78% of businesses like hers.</li><li>22% of the revenue she allocates to her campaign is being used in the wrong areas.</li>",
    "Marta\u2019s online store sells accessories for a widely used smartphone, and her current customer base shares a\u2026": "<li>Web browser</li><li>Budget</li><li>Budget type</li><li><span style=\"text-decoration: underline;\"><strong>Location</strong></span></li><li><span style=\"text-decoration: underline;\"><strong>Device type</strong></span></li>",
    "Tara is using Search Audiences to reach her most valuable customers. Which direct benefit might she obtain by using Search Audience?": "<li><span style=\"text-decoration: underline;\"><strong>Delivering a customized message to the right user at the correct bid</strong></span></li><li>Learning granular insights regarding her search network performance</li><li>Getting suggestions on the best automated bid strategies for her campaigns</li><li>Receiving automatically-generated keyword and ad content suggestions</li>",
    "When should you use Remarketing Lists for Search Ads?": "<li>To reach out to new customers that share the behaviors and characteristics of your remarketing audience segments</li><li>To identify loyal customers and expand the reach to those that resemble your customers</li><li>To reach people, based on advanced demographic criteria</li><li><strong><span style=\"text-decoration: underline;\">To reach people who have already engaged with your website in the past</span></strong></li>",
    "Marisol manages the online advertising campaigns for a chain of toy stores with both a physical and an online\u2026": "<li>Search</li><li><span style=\"text-decoration: underline;\"><strong>Shopping</strong></span></li><li>Video</li><li>Display</li>",
    "When running Remarketing Lists for Search Ads campaigns, some audience lists have higher potential to convert": "<li><strong>Reached the checkout page but did not complete the purchase.</strong></li><li><strong>Added an item to the shopping basket but then abandoned it.</strong></li><li><strong>Visited the website in the past 7 days but did not convert.</strong></li><li><strong>Visited the website in the past 28 days but did not convert</strong>.</li>",
    "Leo is in charge of advertising for the clothing lines of a large manufacturer. He uses his Google Ads\u2026": "<li>The recommendations provide general insight from Google.</li><li><strong><span style=\"text-decoration: underline;\">The recommendations are tailored to the specific account.</span></strong></li><li>The recommendations are created by higher-level account executives.</li><li>The recommendations only apply to select keywords.</li>",
    "Peggy owns a house-cleaning service. She built a booking website and is ready to promote her services online\u2026": "<li>Display</li><li>Video</li><li><strong><span style=\"text-decoration: underline;\">Search</span></strong></li><li>Shopping</li>",
    "Karen\u2019s washing machine broke, so she\u2019s conducting a search on Google to find a new one. She sees a number\u2026": "<li>Advertiser campaign count</li><li>Size of ad group</li><li>Campaign type</li><li><span style=\"text-decoration: underline;\"><strong>Ad relevance</strong></span></li><li><span style=\"text-decoration: underline;\"><strong>Advertiser bid</strong></span></li>",
    "Why should campaigns with different marketing objectives be separated into different Performance Planner plans": "<li><span style=\"text-decoration: underline;\"><strong>So that spend is not reallocated between two different marketing objectives</strong></span></li><li>To avoid any potential keyword duplicates between different marketing objectives</li><li>So that seasonal trends can be better identified for each individual marketing objective</li><li>To prevent campaigns from becoming \u201cLimited by Budget\u201d</li>",
    "Google Ads offers a variety of campaign types that determine where your ad will appear and the format in\u2026": "<li>Search, Print, TV, Shopping, and App</li><li><span style=\"text-decoration: underline;\"><strong>Search, Display, Video, Shopping, and App</strong></span></li><li>Search, Display, Video, Print, and App</li><li>Social, Video, App, Audio, and Shopping Ads</li>",
    "Ideally, what\u2019s the minimum number of values you should aim for per header when using structured snippet\u2026": "<li><span style=\"text-decoration: underline;\"><strong>4</strong></span></li><li>3</li><li>5</li><li>6</li>",
    "Brenda\u2019s working on improving a Google Search Ad\u2019s quality score so it potentially gets a better ad rank and\u2026": "<li>Making the headline bold to potentially improve the eCTR.</li><li>Using colors in the message text to improve Quality Score.</li><li><span style=\"text-decoration: underline;\"><strong>Adding seasonal messaging during the holiday season.</strong></span></li><li>Incorporating an image to make the ad more enticing.</li>",
    "What is one of the reasons why an advertiser should consider using Performance Planner on a monthly basis?": "<li>A / B testing</li><li>Google Ads are updated automatically</li><li>Click-through rate averages require planning</li><li><strong><span style=\"text-decoration: underline;\">Auctions fluctuate all the time</span></strong></li>",
    "Ben is currently managing a campaign that has a total investment of $7,000, generates 1,400 conversions\u2026": "<li>An investment of $9,100 to generate 1,300 conversions and a CPA of $7</li><li>An investment of $8,400 to generate 1,400 conversions and a CPA of $6</li><li><span style=\"text-decoration: underline;\"><strong>An investment of $9,600 to generate 1,600 conversions with a CPA of $6</strong></span></li><li>An investment of $9,800 to generate 1,400 conversions and a CPA of $7</li>",
    "What is a valid recommendation that the Performance Planner can provide?": "<li>Create alternative versions of best performing ad variations</li><li>Apply specific bid adjustments to device and location targeting</li><li>Add a themed group of negative keywords</li><li><strong><span style=\"text-decoration: underline;\">Set a specific target CPA (cost-per-acquisition)</span></strong></li>",
    "Pete is the marketing director for an electric car company. He recently chose \u201cleads\u201d as his Google Search\u2026": "<li>Have more people view his website.</li><li>Encourage customers to purchase electric cars.</li><li><span style=\"text-decoration: underline;\"><strong>Increase e-mail list sign-ups from potential customers.</strong></span></li><li>Promote videos that speak to the business mission.</li>",
    "Gina wants to be able to try out multiple combinations of headlines and descriptions in order to optimize her": "<li>Longer funnels</li><li>Less click-fraud</li><li>Lower eCTR</li><li><span style=\"text-decoration: underline;\"><strong>Greater flexibility</strong></span></li><li><span style=\"text-decoration: underline;\"><strong>More relevance</strong></span></li>",
    "Bob\u2019s electronics company is launching the sale of a new television, UltraView1000. Bob decides to use phrase match in his Search Ads campaign because he wants searches that contain UltraView1000 to show his ad. How else will phrase match benefit Bob\u2019s campaign": "Correct Answer is:<br><strong>Bob\u2019s ad will show on searches for UltraView1000 and additional words before and after.</strong>",
    "Theo is looking to improve his Google Search Ads campaign. On his Google Ads Recommendations page, he notices": "<li>The campaign needs a 75% improvement to be fully optimized.</li><li><span style=\"text-decoration: underline;\"><strong>The campaign could improve up to 25% by following the listed recommendations.</strong></span></li><li>The campaign is performing 25% under budget.</li><li>The campaign is performing better than 75% of all search campaigns.</li>",
    "Why does automating your bid vs. using manual bidding contribute to a successful Google Ads campaign?": "<li>User intent and likelihood to complete valuable actions for your business don\u2019t vary based on location, time, or device.</li><li>The customer journey has become more complex and therefore bids should be based on general user behavior.</li><li>The appropriate bid can often be a static target that\u2019s challenging to reach.</li><li><strong><span style=\"text-decoration: underline;\">If you don\u2019t bid efficiently, you could miss valuable conversions.</span></strong></li>",
    "When creating a text ad for the Search Network, advertisers will need to include three distinct components.": "<li>The analytics</li><li>The landing page</li><li>The site tag</li><li><strong><span style=\"text-decoration: underline;\">The description</span></strong></li>",
    "You can leverage Google Ads\u2019 automated bidding strategy to help get the most from your advertising budget.": "fuck you",
    "Jasmine is the director of marketing for a chain of clothing stores. She\u2019s been given a set budget and needs": "<li>Target impression share</li><li>Target return on ad spend (tROAS)</li><li>Maximize conversions</li><li><strong><span style=\"text-decoration: underline;\">Maximize clicks</span></strong></li>",
    "When are automated extensions, such as Seller Ratings, shown?": "<li>When an advertiser manually opts in to receive them.</li><li>When an automated extension campaign is created.</li><li><span style=\"text-decoration: underline;\"><strong>When Google predicts they\u2019ll improve ad performance.</strong></span></li><li>When an account is white-listed for them.</li>",
    "Tomacz wants to use a Google Search Ads campaign to capture the attention of customers searching for camping": "<li>Potential customers can search the ads for specific products.</li><li><span style=\"text-decoration: underline;\"><strong>Displayed ads are relevant to a potential customer\u2019s Google search.</strong></span></li><li>Ads appear intermixed with organic search results.</li><li>Ads send follow-up information to the potential customer.</li>",
    "Sandy, an expert on Search marketing, knows she should use extensions effectively in order to optimize her": "<li>Use ad extensions only when advertising the service industry.</li><li>Use no more than two extensions per campaign or ad group.</li><li>Use at least five extensions and add only to ad groups.</li><li><strong><span style=\"text-decoration: underline;\">Use at least three extensions in each campaign or ad group.</span></strong></li>",
    "With Dynamic Search Ads, what does the advertiser provide?": "<li><span style=\"text-decoration: underline;\"><strong>A list of web pages</strong></span></li><li>A list of search terms</li><li>A machine-learning algorithm</li><li>A headline</li>",
    "As a digital strategist, Jared wants to add something extra to his ads to give users more incentive to click..": "<li>Unlimited number of characters in each</li><li>Up to 10 characters in each</li><li>Up to 10 characters in one and 5 in another, for a total of 15</li><li><strong><span style=\"text-decoration: underline;\">Up to 15 characters in each</span></strong></li>",
    "Why should your business use Performance Planner?": "<li>It validates budgets against other vendors in the same market.</li><li>It is the only ad budgeting software on the market.</li><li><span style=\"text-decoration: underline;\"><strong>It makes recommendations that are validated using machine learning.</strong></span></li><li>It helps businesses determine a go-to-market strategy.</li>",
    "How can ad extensions contribute to increasing user engagement?": "<li>With attractive images and videos.</li><li>Ad extensions include a \u201cshare\u201d button.</li><li>Ad extensions include a \u201clike\u201d button to gauge if an ad is favorable.</li><li><strong><span style=\"text-decoration: underline;\">By addressing a user\u2019s intent, device, and location.</span></strong></li>",
    "Organize these steps in the correct order to set up an effective Customer Match strategy\u2026": "<li><strong>Segment a\ncustomer list, based on a desired marketing action.</strong></li><li><strong>Upload the\nlist to Google Ads.</strong></li><li><strong>Translate the\nlist into an audience list and make it available for targeting.</strong></li><li><strong>Customize\nyour creatives with special offers or incentives that are specific to this\naudience.</strong></li>",
    "You manage marketing for a small business on a tight budget, yet you need to reach as many people as possible.": "<li>With Google Ads, your ads will show on every available search engine.</li><li>With Google Ads you always pay using cost-per-reach, predetermined by your budget.</li><li>Google Ads saves you time by deciding what your budget will be on a daily basis.</li><li><strong><span style=\"text-decoration: underline;\">With Google Ads, you can choose a maximum amount to spend per month.</span></strong></li>",
    "Which Search Audience solution would assist you in finding new customers that share the behaviors and\u2026": "<li>In-Market Audiences</li><li>Customer Match</li><li>Affinity Audiences</li><li><strong><span style=\"text-decoration: underline;\">Similar Audiences for Search</span></strong></li>",
    "Laverne created her first Google Search campaign for her yoga school. She selects the Google Search Network\u2026": "<li>Enables her to partner with other similar businesses.</li><li>Allows her to reach to all device types.</li><li><span style=\"text-decoration: underline;\"><strong>Extends her reach to additional sites.</strong></span></li><li>Increases the geographic distribution of her ad.</li>",
    "Rina notices that her ad\u2019s average cost per click (CPC) is significantly higher than the industry benchmark\u2026": "<li>Decrease the number of ad groups.</li><li>Match the bid to an industry benchmark.</li><li>Increase the number of ad groups.</li><li><strong><span style=\"text-decoration: underline;\">Improve the ad\u2019s quality score.</span></strong></li>",
    "Mary is tasked with designing an advertising campaign for her company, an online pet food store and app\u2026": "<li>Social, Display, Video, Shopping, and App</li><li>Search, Display, TV, Shopping, and App</li><li><span style=\"text-decoration: underline;\"><strong>Search, Display, Video, Shopping, and App</strong></span></li><li>Search, Display, Video, App, and Access</li>",
    "Which user data can be uploaded when creating a Customer Match strategy? (Choose two.)\u2026": "<li><span style=\"text-decoration: underline;\"><strong>E-mail address</strong></span></li><li><span style=\"text-decoration: underline;\"><strong>Mailing address</strong></span></li><li>Employment status</li><li>Age</li><li>Highest level of education</li>",
    "Marta has a tight marketing budget and needs to use a strategy that can drive customers to her website\u2026": "<li>Target cost-per-acquisition (tCPA)</li><li>Target impression share</li><li>Target return on ad spend (Target ROAS)</li><li><strong><span style=\"text-decoration: underline;\">Maximize clicks</span></strong></li>",
    "Each Similar Audience has its seed list members removed to ensure what?": "<li>That only highly-relevant traffic is targeted</li><li><span style=\"text-decoration: underline;\"><strong>That no user overlaps between a similar list and its seed list</strong></span></li><li>That ads are shown in competitive positions</li><li>That ads do not risk double-serving</li>",
    "Jamie wants to focus on selling her overstocked blue saucepans. She sets up keywords using a broad-match\u2026": "<li><span style=\"text-decoration: underline;\"><strong>She doesn\u2019t have to think of all the related saucepan keywords.</strong></span></li><li><span style=\"text-decoration: underline;\"><strong>She can easily select the color she wants to focus on.</strong></span></li><li>She can explicitly choose keywords to ignore.</li><li>Her ad will only show for \u201cblue saucepans.\u201d</li><li>She can choose the exact searches her keywords will match.</li>"
}
import re
clean_dict = {}
for key in test:


    test[key].replace('<strong><span style=\"text-decoration: underline;\">', 'style=text-decoration: underline;">')
    test[key].replace('style=\"text-decoration: underline;\"><strong>', 'style=text-decoration: underline;">')
    test[key] = test[key].replace('\n', ' ')

    #answer_list = [x.group() for x in re.finditer( r'<li><strong>(.*?)<\/strong><\/li>', test[key])]
    if "Correct Answer is:" in test[key]:
        answer_list = [x.group(1) for x in re.finditer( r'<strong>\d.(.*?)<\/strong>', test[key])]
        if len(answer_list) < 1:
            answer_list = [x.group(1) for x in re.finditer( r'<strong>(.*?)<\/strong>', test[key])]
    
    else:
        answer_list = [x.group() for x in re.finditer( r'text-decoration: underline;">(.*?)<\/span>', test[key])]

    if len(answer_list) < 1:
        answer_list = [x.group(1) for x in re.finditer( r'<strong>(.*?)<\/strong>', test[key])]
    

    

    #clea_list = [x.replace('<li><strong>','').replace('</strong></li>','') for x in answer_list]

    clea_list = [x.replace('text-decoration: underline;">','').replace('<strong>','').replace('</strong>','').replace('</span>','')for x in answer_list]

    #print(clea_list)

    print('"'+str(key)+'"'+': '+str(clea_list).replace("'",'"')+",")

