to_trim = {"You want to improve the relevance of an ad with a particular set of keywords. The goal is to increase the…": ["Adding more negative keywords."],
"When creating an ad, how does Greg know what it will look like to his potential customers?": ["As he types in his URL, headline, and description, a preview of the mobile and desktop versions of his ad will appear."],
"Asam is learning about Google Ads Search. He wants to know why a marketer might use callout extensions. For which activity are callout extensions beneficial?": ["Highlight key information and unique selling points of a business"],
"Google Ads was designed to help businesses achieve online success. To accomplish this, Google Ads was built…": ["Relevance, control, and results"],
"Your client, Vince’s Veggies, wants to increase downloads of their popular recipe printouts. You suggest they create ad groups based on the cooking categories that appear on their website. What will they need to create in their first Google Search Ad group? (Choose two.)": ["Keyword list", "Default bid amount"],
"What’s the maximum number of ad extensions that can show for a particular query or device at any given time?": ["4"],
"What is a main benefit of using Search Audience solutions?": ["They can help send the right message to the right customer with the right bid."],
"A water-sports company specializes in custom-made watercrafts and accessories. Their marketing manager…": ["A green boat paddle", "Travel on a paddle ship"],
"What does Performance Planner automatically do?": ["Forecasts how your current campaigns will perform in the future"],
"Clara is an advertising director who has been tasked with optimizing her company’s Google Search campaign…": ["To find how close her campaign is from potential ideal results"],
"Siona needs to make sure her ads are getting a minimum number of impressions on the top of the page…": ["Target impression share"],
"Which statement is true about serving relevant ad extensions?": ["They encourage users to make more informed decisions and take action."],
"Jimmy sells televisions on his website. He notices he’s getting traffic from searches for a brand he…": ["His ads won’t be shown to users searching for the uncarried brand."],
"What is the minimum number of users a remarketing list must have before being used with a Remarketing…": ["1,000 users"],
"You’re working on a Google Search Ad that’s not performing as expected. You specifically want more users to…": ["Changing the call-to-action message of the ad."],
"Match these Search Audience solutions with the benefits they can bring to": ["Remarketing Lists for Search Ads ", "Detailed Demographics", "In-Market Audiences ", "Customer Match"],
"Your Google Search text ad has three main components. The first is a headline, and the second is a description": ["The URL displaying your website address."],
"Reggie manages the online marketing campaigns for a vitamin and supplement store. He launched a…": ["Getting more customers to learn about his products."],
"You’d like to improve an ad’s perceived quality during an ad auction. What aspect of the ad will be most…": ["Improving the navigability of the landing page."],
"Brian manages his company’s Google Search Ads campaign. He regularly reviews the optimization score to make…": ["Key aspects of his accounts, including statistics, settings, and industry trends"],
"Silly Sayings is seeing a lot of website traffic, but the company wants to generate more qualified leads…": ["By providing users with relevant information up-front."],
"What Search Network text ad component provides up to three fields of 30 characters each?": ["The headline component"],
"Rashid wants to raise awareness of his brand and build campaigns focused on branded terms. He doesn’t have…": ["Target impression share"],
"Carrie owns a gardening store and uses a website to promote all the products she sells. A user saw a Google…": ["Searching for related gardening information."],
"John’s company makes a great product and customers are happy with their purchases. Unfortunately, few…": ["With multiple headline and description options, responsive ads can compete in more auctions for a wider range of search terms.", "With lower costs-per-click, advertisers using responsive ads can afford to be in more daily auctions."],
"You’ve been tasked with marketing a new line of plumbing services, but you have a set budget you can’t exceed.": ["Google Ads gives you control over your budget."],
"Karen has evaluated her Google Search Ads campaign’s optimization score after noticing that the campaign’s…": ["It will improve upon acceptance."],
"Swee Yin’s fashion-apparel department store runs a popular biannual sale on men’s hats, with large discounts and surprise bonus items. She wants to tailor her Google Search campaign to highlight this sale. How can Google Search campaigns be tailored to promote her company’s sales event?": ["By creating a new ad group for the sale.", "By setting campaign start/end dates."],
"A golf enthusiast regularly watches instructional videos about golf, has recently searched for the best golf…": ["Affinity Audience"],
"Samira recently opened an online potted plant store and needs to promote it. She chose Google Ads because…": ["Shopping campaigns, which promote her products by giving consumers detailed informationabout what she’s selling before they click her ad."],
"When visibility is the campaign goal, which bidding strategy should an advertiser choose?": ["Target impression share"],
"Yan wants to attract customers specifically searching on Google for Time-B-Gone, his company’s unique office…": ["Landing pages from standard ad groups"],
"You are working to improve the quality score of a Google Search ad by increasing your eCTR. Your goal is to…": ["Adding more specifics to the ad."],
"Helen’s Heating and Air (HHA) wants to encourage interest in their new smart refrigerators. They know that…": ["Smart refrigerator reviews", "Energy-efficient fridge"],
"John’s Plumbing prides itself on excellent customer service, especially during after-hours service calls…": ["Ad scheduling"],
"Francis wants to increase his Google Ads skills and optimize results for his clients. What two best practices…": ["Include three to five ads, and at least three extensions in each ad group.", "Optimize the campaign’s ad rotation for clicks or conversion actions."],
"Maria has been told that she should use the Performance Planner on a monthly basis. Why should she do so?": ["To react to ever-changing external factors"],
"What are two ways that Performance Planner can help reveal the possibilities across all your Google Ads…": ["Validation", "Simulation"],
"Match each ad extension with the benefit it brings to a user’s ad experience.": [],
"It is 10 a.m. and you are sitting in a train station in London, looking through your calendar on your tablet.": ["Time", "Interest", "Intent", "Device", "Location"],
"Priya only has $500 a month to spend on her campaign, but she needs to drive as many potential customers as…": ["Maximize clicks"],
"Your company provides home-maintenance services, and you want to reach more potential customers…": ["You can set your own budget and can change it at any time."],
"Carlton runs an adventure excursion company in South America. He’d like to increase the number of people…": ["Researching South American holiday destinations online."],
"Google Ads was constructed around three core principles, focused on helping businesses reach their online…": ["Control and results"],
"You’ve seen great results from your Google Search campaigns when using Remarketing Lists for Search Ads…": ["Use Similar Audiences to find new visitors for your site"],
"Bernadette’s in charge of marketing a new product in a highly competitive segment. She’s planning to launch…": ["Her business will have a competitive presence with similar businesses during searches."],
"Mario is working on a text ad that will run on the Google Search Network. He filled in each component with…": ["The description component"],
"Rebecca is a marketing executive at an airline company. She has been asked to plan her company’s online…": ["Performance Planner forecasting is powered by billions of Google searches conducted eachweek.", "Performance Planner leverages machine learning for forecasting."],
"What two ad extension types can also be served as automated ad extensions? (Choose two.)": ["Sitelink extension", "Callout extension"],
"An advertising executive takes over a Google Search ads campaign. On his Google Ads Recommendations page he…": ["<a>The campaign could be improved by 60% if the listed recommendations are followed</a>."],
"What’s the primary benefit of using structured snippet extensions in your ads?": ["Gives users specific information about what you’re offering, before they visit your website."],
"Automated bidding does the heavy lifting for advertisers on Google Ads. What does automated bidding use to…": ["Machine learning"],
"Trevor owns a manufacturing business that makes specialized hiking and rock-climbing gear. He’s a small…": ["Display"],
"Bob’s electronics company is launching a new television called UltraView1000. Bob decides to use broad…": ["Bob’s ad will appear if search terms contain some variation of his keyword, such as “TV.”"],
"Yan is working on a Remarketing List for Search Ads campaign. Which user could be added to a valid Remarket…": ["Someone who has added items to a shopping basket on his company’s website but thenabandoned it"],
"As an advertiser, creating your first text ad in Google Ads is a simple five…": ["First step:", "Second Step:", "Third Step:", "Fourth Step:", "Fifth Step: "],
"What’s a key objective in delivering ad extensions?": ["Providing the right users with the right information at the right moment."],
"Ad extensions assist in providing users with which two things they want from their search experience?": ["Relevant information", "Information based on their moment"],
"Ginger’s working on creating her first Google Search Ad. She wants to create an inviting and relevant ad,…": ["has a relevant headline", "includes a current promotion"],
"Lisa sells kitchen furniture through her website. While her sales are stable, she’s concerned that they’re…": ["Her business will have a competitive presence with similar businesses during searches."],
"Jerry’s managing a Google Search campaign and would like to improve the position in which his ads appear…": ["Create a helpful, relevant landing page for the ad."],
"What are two main benefits of using Search Audience solutions? (Choose two.)": ["Making the right bids when certain groups of people are searching for your product or services", "Reaching different audience segments with unique messaging that is highly relevant to them"],
"How is using non-last-click attribution conversions useful for Performance Planner forecasts?": ["To allocate budgets that drive incremental conversions"],
"What can the Performance Planner assist you with?": ["To improve return on investment so you can drive more conversions within your target CPA(cost-per-acquisition)"],
"What does layering an Affinity audience with a broad keyword targeting campaign help you do?": ["Ensure your ads are only seen by people who have demonstrated a qualified interestin your service and/or product(s)"],
"What is one way that Performance Planner helps businesses increase sales?": ["By maximizing the number of conversions for a spend scenario"],
"Steven is an advertising executive at a large auto parts company. He uses his Google Ads Recommendations…": ["Apply recommendations across multiple layers of his advertising strategy"],
"Singh’s marketing company has created an enticing ad that receives many clicks. What effect will the ad…": ["The higher expected click-through rate will lead to a higher Ad Rank."],
"Mary wants to run a text ad on the Google Search Network. She’s new to text ads and needs to start with the…": ["Headline, URL, Description"],
"How can Performance Planner serve your business?": ["By optimizing your ad budget for maximum growth"],
"Wendy is setting up a Customer Match strategy to reach a list of prospective customers. What must she provide?": ["Customer relationship management data"],
"Jim has created a Google Search ad with a bid of $5. Two other advertisers in an auction have bids of $2.50…": ["$2.51"],
"Trina is using automated bidding as part of her Google Ads Search bidding strategy. Why might she prefer…": ["Machine learning helps her set the appropriate bid for each and every auction."],
"Why is using the performance targets feature after utilizing the Performance Planner recommended?": ["This practice allows you to monitor targets set in the Performance Planner and to receive alerts and recommendations when a campaign is not on track."],
"What are two ways Dynamic Search Ads brings value to an advertising campaign?": ["It creates new ads automatically.", "It finds traffic an advertiser might miss."],
"Your Google Search Ads optimization score is calculated by an algorithm that looks across key aspects of…": ["Industry data", "Account settings"],
"Google Ads reviews saved text ads to ensure they meet advertising policies before being shown to users…": ["Content and formatting."],
"What’s an example of an effective callout extension?": ["Free returns"],
"While managing a successful Google Ads campaign, why would you choose automated bidding instead of manual…": ["Because given the dynamic nature of Google’s auctions, the appropriate bid can often be a moving target that is challenging to reach at scale when using manual bidding"],
"What does adding callout extensions to your Google Search ads enable you to do?": ["Highlight information about value-adding attributes of your business, products, orservices."],
"Bob’s electronics company has quite a buzz around a new television they’re launching, called UltraView1000…": ["Bob’s ad will appear if search terms contain at least all three of the keywords orvariations of those terms."],
"You want to increase the relevance of a Google Search Ad so it’s more meaningful to potential customers…": ["Selecting distinct geographic areas.", "Selecting only relevant languages in campaign setup."],
"What content could be used for a structured snippet extension?": ["Berlin, London, Paris, Singapore"],
"Hank wants to use a “Maximize Conversions” campaign with the Performance Planner. Which recommendation…": ["A recommended average daily budget"],
"Which is required for an ad to be served to a user?": ["The keywords must be relevant to the search term."],
"Samira has been tasked with increasing the relevance of her company’s ads. She has been told that she can…": ["Up to 15 headlines"],
"Using the Performance Planner on a monthly basis allows you to optimize which two aspects of an account?": ["Bids", "Budgets"],
"Alex has started a Google Search campaign designed to promote his online motorcycle accessories store…": ["By showing his ad to people searching for related information about helmets."],
"What can the Performance Planner recommend?": ["Campaign-level Target CPA (cost-per-acquisition)"],
"What’s an accurate description of callout extensions?": ["Short, specific snippets of text that highlight value-adding attributes."],
"Trina sells dolls and accessories, and doesn’t have much time to update her Search campaigns with her ever…": ["Keyword lists can be automatically created based on website offerings."],
"Sarah’s Autos sells multiple automobile brands, showcasing used, pre-owned, and new vehicles. The company’s…": ["Car", "Automobile"],
"Which Dynamic Search Ads option allows an advertiser to group web pages under custom labels?": ["Page feeds"],
"Francine is advertising her company’s newest video-editing software and related products. She knows that…": ["More ads in an ad group means more options for success in an auction."],
"In-Market audiences would be suited to reach which user?": ["Someone looking to purchase a new car"],
"What ad extension is only available as a full automated ad extension?": ["Seller ratings extension"],
"How does automating your bid contribute to a successful Google Ads campaign?": ["Automated bidding uses machine learning to algorithmically help you set the appropriatebid for each and every auction."],
"Google Ads was designed to deliver three things to every advertiser: relevance, control, and results…": ["By giving advertisers control over the maximum they spend per month."],
"After running a Google Search Ads campaign for several months, Meredith notices sales of her advertised…": ["The campaign could be improved by 78% if the listed recommendations are followed."],
"Marta’s online store sells accessories for a widely used smartphone, and her current customer base shares a…": ["Location", "Device type"],
"Tara is using Search Audiences to reach her most valuable customers. Which direct benefit might she obtain by using Search Audience?": ["Delivering a customized message to the right user at the correct bid"],
"When should you use Remarketing Lists for Search Ads?": ["To reach people who have already engaged with your website in the past"],
"Marisol manages the online advertising campaigns for a chain of toy stores with both a physical and an online…": ["Shopping"],
"When running Remarketing Lists for Search Ads campaigns, some audience lists have higher potential to convert": ["Reached the checkout page but did not complete the purchase.", "Added an item to the shopping basket but then abandoned it.", "Visited the website in the past 7 days but did not convert.", "Visited the website in the past 28 days but did not convert"],
"Leo is in charge of advertising for the clothing lines of a large manufacturer. He uses his Google Ads…": ["The recommendations are tailored to the specific account."],
"Peggy owns a house-cleaning service. She built a booking website and is ready to promote her services online…": ["Search"],
"Karen’s washing machine broke, so she’s conducting a search on Google to find a new one. She sees a number…": ["Ad relevance", "Advertiser bid"],
"Why should campaigns with different marketing objectives be separated into different Performance Planner plans": ["So that spend is not reallocated between two different marketing objectives"],
"Google Ads offers a variety of campaign types that determine where your ad will appear and the format in…": ["Search, Display, Video, Shopping, and App"],
"Ideally, what’s the minimum number of values you should aim for per header when using structured snippet…": ["4"],
"Brenda’s working on improving a Google Search Ad’s quality score so it potentially gets a better ad rank and…": ["Adding seasonal messaging during the holiday season."],
"What is one of the reasons why an advertiser should consider using Performance Planner on a monthly basis?": ["Auctions fluctuate all the time"],
"Ben is currently managing a campaign that has a total investment of $7,000, generates 1,400 conversions…": ["An investment of $9,600 to generate 1,600 conversions with a CPA of $6"],
"What is a valid recommendation that the Performance Planner can provide?": ["Set a specific target CPA (cost-per-acquisition)"],
"Pete is the marketing director for an electric car company. He recently chose “leads” as his Google Search…": ["Increase e-mail list sign-ups from potential customers."],
"Gina wants to be able to try out multiple combinations of headlines and descriptions in order to optimize her": ["Greater flexibility", "More relevance"],
"Bob’s electronics company is launching the sale of a new television, UltraView1000. Bob decides to use phrase match in his Search Ads campaign because he wants searches that contain UltraView1000 to show his ad. How else will phrase match benefit Bob’s campaign": ["Bob’s ad will show on searches for UltraView1000 and additional words before and after."],
"Theo is looking to improve his Google Search Ads campaign. On his Google Ads Recommendations page, he notices": ["The campaign could improve up to 25% by following the listed recommendations."],
"Why does automating your bid vs. using manual bidding contribute to a successful Google Ads campaign?": ["If you don’t bid efficiently, you could miss valuable conversions."],
"When creating a text ad for the Search Network, advertisers will need to include three distinct components.": ["The description"],
"You can leverage Google Ads’ automated bidding strategy to help get the most from your advertising budget.": [],
"Jasmine is the director of marketing for a chain of clothing stores. She’s been given a set budget and needs": ["Maximize clicks"],
"When are automated extensions, such as Seller Ratings, shown?": ["When Google predicts they’ll improve ad performance."],
"Tomacz wants to use a Google Search Ads campaign to capture the attention of customers searching for camping": ["Displayed ads are relevant to a potential customer’s Google search."],
"Sandy, an expert on Search marketing, knows she should use extensions effectively in order to optimize her": ["Use at least three extensions in each campaign or ad group."],
"With Dynamic Search Ads, what does the advertiser provide?": ["A list of web pages"],
"As a digital strategist, Jared wants to add something extra to his ads to give users more incentive to click..": ["Up to 15 characters in each"],
"Why should your business use Performance Planner?": ["It makes recommendations that are validated using machine learning."],
"How can ad extensions contribute to increasing user engagement?": ["By addressing a user’s intent, device, and location."],
"Organize these steps in the correct order to set up an effective Customer Match strategy…": ["Segment a customer list, based on a desired marketing action.", "Upload the list to Google Ads.", "Translate the list into an audience list and make it available for targeting.", "Customize your creatives with special offers or incentives that are specific to this audience."],
"You manage marketing for a small business on a tight budget, yet you need to reach as many people as possible.": ["With Google Ads, you can choose a maximum amount to spend per month."],
"Which Search Audience solution would assist you in finding new customers that share the behaviors and…": ["Similar Audiences for Search"],
"Laverne created her first Google Search campaign for her yoga school. She selects the Google Search Network…": ["Extends her reach to additional sites."],
"Rina notices that her ad’s average cost per click (CPC) is significantly higher than the industry benchmark…": ["Improve the ad’s quality score."],
"Mary is tasked with designing an advertising campaign for her company, an online pet food store and app…": ["Search, Display, Video, Shopping, and App"],
"Which user data can be uploaded when creating a Customer Match strategy? (Choose two.)…": ["E-mail address", "Mailing address"],
"Marta has a tight marketing budget and needs to use a strategy that can drive customers to her website…": ["Maximize clicks"],
"Each Similar Audience has its seed list members removed to ensure what?": ["That no user overlaps between a similar list and its seed list"],
"Jamie wants to focus on selling her overstocked blue saucepans. She sets up keywords using a broad-match…": ["She doesn’t have to think of all the related saucepan keywords.", "She can easily select the color she wants to focus on."],
}

import json



json_fun = {}
counter = 0
for key in to_trim:
    json_fun[str(counter)] = {'question':key.lower(), 'answer':[x.lower() for x in to_trim[key]]}
    counter += 1




with open("/well_formatted_qa.json", 'w') as fps:
    json.dump(json_fun, fps)





    


